name: Get new request

on:
  workflow_dispatch:
  issues:
    types: [closed]
  schedule:
    - cron: "10 14 * * 0"

jobs:
  search:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Authenticate with GitHub
        run: |
          Install-Module PowerShellForGitHub -Force -ErrorAction SilentlyContinue
          Import-Module PowerShellForGitHub
          $secureString = ("${{ secrets.GITHUB_TOKEN }}" | ConvertTo-SecureString -AsPlainText -Force)
          $cred = New-Object System.Management.Automation.PSCredential "username is ignored", $secureString
          Set-GitHubAuthentication -Credential $cred
          $cred = $null
        shell: pwsh
      - name: Check requests
        run: |
          Import-Module PowerShellForGitHub
          Set-GitHubConfiguration -DisableTelemetry
          Set-Location ${{ github.workspace }}
          & ".\tools\looknewer.ps1"