name: Package improver

on:
  push:
    branches: [master]

jobs:
  updater:
    runs-on: windows-2022
    defaults:
      run:
        shell: powershell

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 100

      - name: Configure git client
        run: |
          git config --global user.email "helpdesk.choc@gmail.com"
          git config --global user.name "Tunisiano"
          git config --global core.safecrlf false
          git checkout master

      - name: Checking nuspec errors
        run: |
          scripts/Find-NuspecError.ps1
          git commit -am "Nuspec errors"

      - name: Checking packageSourceUrl
        run: |
          scripts/Update-PackageSourceUrl.ps1 -GithubRepository "tunisiano187/Choco-packages" -UseStopwatch
          git commit -am "PackageSourceUrl"

      - name: Checking variables in ps1
        run: |
          scripts/Update-Variables.ps1
          git commit -am "ps1 vars"

      - name: Checking IconUrl in nuspec
        run: |
          scripts/Update-IconUrl.ps1 -Quiet -GithubRepository "tunisiano187/Choco-packages" -UseStopwatch
          git commit -am "Updating icons"
      
      - name: Updating owners in nuspec
        run: |
          import-module Wormies-AU-Helpers
          $nuspec=Get-ChildItem ./*.nuspec -Recurse;
          foreach ($file in $nuspec) { Update-Metadata -key owners -value "tunisiano" -NuspecFile $file.FullName }
          git commit -am "Updating owner"

      - name: Updating Packages.md
        run: |
          scripts/ListPackages.ps1
          git commit -am "List packages"