name: Package improver

on:
  push:
    branches: [master]

jobs:
  updater:
    runs-on: windows-2022
    defaults:
      run:
        shell: powershell

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 100

      - name: Configure git client
        run: |
          git config --global user.email "helpdesk.choc@gmail.com"
          git config --global user.name "Tunisiano"
          git config --global core.safecrlf false
          git checkout master

      - name: Checking nuspec errors
        run: |
          $ErrorActionPreference = 'SilentlyContinue';
          scripts/Find-NuspecError.ps1
          try {
            git commit -am "Nuspec errors"
          } catch {
              write-output "Nuspec errors : nothing to commit"
          }

      - name: Checking packageSourceUrl
        run: |
          $ErrorActionPreference = 'SilentlyContinue';
          scripts/Update-PackageSourceUrl.ps1 -GithubRepository "tunisiano187/Choco-packages" -UseStopwatch
          try {
            git commit -am "PackageSourceUrl"
          } catch {
              write-output "PackageSourceUrl : nothing to commit"
          }
          

      - name: Checking variables in ps1
        run: |
          $ErrorActionPreference = 'SilentlyContinue';
          scripts/Update-Variables.ps1
          try {
            git commit -am "ps1 vars"
          } catch {
              write-output "ps1 vars : nothing to commit"
          }

      - name: Checking IconUrl in nuspec
        run: |
          $ErrorActionPreference = 'SilentlyContinue';
          scripts/Update-IconUrl.ps1 -Quiet -GithubRepository "tunisiano187/Choco-packages" -UseStopwatch
          try {
            git commit -am "Updating icons"
          } catch {
              write-output "Updating icons : nothing to commit"
          }
      
      - name: Updating owners in nuspec
        run: |
          $ErrorActionPreference = 'SilentlyContinue';
          import-module Wormies-AU-Helpers
          $nuspec=Get-ChildItem ./*.nuspec -Recurse;
          foreach ($file in $nuspec) { Update-Metadata -key owners -value "tunisiano" -NuspecFile $file.FullName }
          try {
            git commit -am "Updating owner"
          } catch {
              write-output "Updating owner : nothing to commit"
          }

      - name: Updating Packages.md
        run: |
          $ErrorActionPreference = 'SilentlyContinue';
          scripts/ListPackages.ps1
          try {
            git commit -am "List packages"
          } catch {
              write-output "List packages : nothing to commit"
          }